### ISSUE TITLE
Could we get an example of valid  jsonData for a TypedDataVersion.V4 call?

### ISSUE THREAD

**Issue by bobwith2bees** [wakumo/eth-sig-util#4]
Specifically how the 'types' are mapped to valid Json for a TypedDataVersion.V4 call? 

```
E/flutter ( 7237): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): jsonData format is not corresponding to TypedMessage
E/flutter ( 7237): #0      TypedDataUtil.hashMessage (package:eth_sig_util/util/typed_data.dart:45:9)
E/flutter ( 7237): #1      EthSigUtil.signTypedData (package:eth_sig_util/eth_sig_util.dart:26:27)
```

An example of the  typed data I am trying to sign is on step three of this page https://docs.rarible.org/asset/creating-an-asset#erc721-lazy-minting

I have this, but I don't know how to format it properly for the signTypedData 'types' field.

```
"types": {
    "EIP712Domain" [
      {
        type: "string",
        name: "name",
      },
      {
        type: "string",
        name: "version",
      },
      {
        type: "uint256",
        name: "chainId",
      },
      {
        type: "address",
        name: "verifyingContract",
      }
    ],
    "Mint721": [
        { name: "tokenId", type: "uint256" },
        { name: "tokenURI", type: "string" },
        { name: "creators", type: "Part[]" },
        { name: "royalties", type: "Part[]" }
    ],
    "Part": [
        { name: "account", type: "address" },
        { name: "value", type: "uint96" }
    ]
},
```

Thanks for your time.  Excited to see this package.

**Comment by ludowkm** [comment]
hi @bobwith2bees , thank you for your report, i also faced this issue and have fixed it already, let's checkout version 0.0.3
